export const BROWSER_MODELS = [
    {
        id: 'browser:mobilenet',
        name: 'MobileNet',
        usageLabel: 'Imagenes',
        runtime: 'browser',
        modelType: 'mobilenet',
        task: 'Clasificacion de imagenes',
        algorithm: 'CNN MobileNet',
        efficiency: 'Rapido',
        modeLabel: 'Imagen/camara',
        supportsWebcam: true,
        description: 'Clasifica la imagen completa y devuelve las etiquetas generales mas probables. Es adecuado para reconocer escenas u objetos dominantes, pero no localiza regiones especificas dentro de la imagen.'
    },
    {
        id: 'browser:coco-ssd',
        name: 'COCO-SSD',
        usageLabel: 'Objetos',
        runtime: 'browser',
        modelType: 'coco-ssd',
        task: 'Deteccion de objetos',
        algorithm: 'Single Shot Detector',
        efficiency: 'Medio',
        modeLabel: 'Imagen/camara',
        supportsWebcam: true,
        description: 'Detecta multiples objetos comunes, como personas, vehiculos, animales y elementos cotidianos. Devuelve una caja por objeto detectado y funciona bien para imagenes con varios elementos.'
    },
    {
        id: 'browser:blazeface',
        name: 'BlazeFace',
        usageLabel: 'Rostros',
        runtime: 'browser',
        modelType: 'blazeface',
        task: 'Deteccion de rostros',
        algorithm: 'Detector ligero inspirado en SSD',
        efficiency: 'Rapido',
        modeLabel: 'Imagen/camara',
        supportsWebcam: true,
        description: 'Detecta rostros con baja latencia y usa puntos faciales basicos para ajustar mejor el recuadro. Es util para webcam, selfies o validaciones rapidas de presencia facial.'
    },
    {
        id: 'browser:handpose',
        name: 'HandPose',
        usageLabel: 'Manos',
        runtime: 'browser',
        modelType: 'handpose',
        task: 'Deteccion de manos',
        algorithm: 'Regresion de 21 puntos de mano',
        efficiency: 'Lento',
        modeLabel: 'Imagen/camara',
        supportsWebcam: true,
        description: 'Estima 21 puntos clave de la mano para ubicar dedos, palma y muneca. Es mas pesado que los detectores simples, pero permite recuadros ajustados a la postura real de la mano.'
    },
    {
        id: 'browser:body-pix',
        name: 'BodyPix',
        usageLabel: 'Personas',
        runtime: 'browser',
        modelType: 'body-pix',
        task: 'Segmentacion de persona',
        algorithm: 'Segmentacion con MobileNet',
        efficiency: 'Lento',
        modeLabel: 'Imagen/camara',
        supportsWebcam: true,
        description: 'Segmenta pixeles pertenecientes a una persona y separa la silueta del fondo. Es util para mascaras, presencia humana y recorte aproximado, aunque consume mas recursos en webcam.'
    }
];

export const CUSTOM_MODEL_SLOTS = [
    {
        id: 'backend:custom-yolo-v8-v11-detector',
        backendId: 'custom-yolo-v8-v11-detector',
        name: 'YOLOv8 / YOLOv11',
        usageLabel: 'Objetos',
        runtime: 'backend',
        task: 'Deteccion de objetos',
        algorithm: 'Ultralytics YOLO',
        efficiency: 'Medio',
        modeLabel: 'Solo imagen',
        status: 'ready',
        statusLabel: 'Listo',
        supportsWebcam: false,
        description: 'Identifica objetos comunes dentro de una imagen, como personas, vehiculos, animales y elementos cotidianos. Es una buena opcion general cuando quieres resultados equilibrados.'
    },
    {
        id: 'backend:custom-faster-rcnn-detector',
        backendId: 'custom-faster-rcnn-detector',
        name: 'Faster R-CNN',
        usageLabel: 'Objetos',
        runtime: 'backend',
        task: 'Deteccion de objetos',
        algorithm: 'Region Proposal Network + CNN',
        efficiency: 'Lento',
        modeLabel: 'Solo imagen',
        status: 'trained',
        statusLabel: 'Entrenado',
        supportsWebcam: false,
        description: 'Analiza la imagen con mas detalle para encontrar objetos y reducir detecciones apresuradas. Es util cuando prefieres revisar con mas cuidado aunque tarde mas.'
    },
    {
        id: 'backend:custom-retinanet-detector',
        backendId: 'custom-retinanet-detector',
        name: 'RetinaNet',
        usageLabel: 'Objetos',
        runtime: 'backend',
        task: 'Deteccion de objetos',
        algorithm: 'Focal Loss + Feature Pyramid Network',
        efficiency: 'Lento',
        modeLabel: 'Solo imagen',
        status: 'trained',
        statusLabel: 'Entrenado',
        supportsWebcam: false,
        description: 'Busca objetos comunes en imagenes donde puede haber elementos pequenos, parcialmente visibles o mezclados con otros. Tiende a ser conservador con las detecciones.'
    },
    {
        id: 'backend:custom-efficientdet-detector',
        backendId: 'custom-efficientdet-detector',
        name: 'EfficientDet',
        usageLabel: 'Objetos',
        runtime: 'backend',
        task: 'Deteccion de objetos',
        algorithm: 'BiFPN + EfficientNet',
        efficiency: 'Medio',
        modeLabel: 'Solo imagen',
        status: 'ready',
        statusLabel: 'Listo',
        supportsWebcam: false,
        description: 'Detecta objetos comunes en imagenes cargadas buscando buen balance entre rapidez y calidad. Es util para pruebas generales sin exigir tanta carga como los modelos mas pesados.'
    },
    {
        id: 'backend:custom-detr-rtdetr-detector',
        backendId: 'custom-detr-rtdetr-detector',
        name: 'DETR / RT-DETR',
        usageLabel: 'Objetos',
        runtime: 'backend',
        task: 'Deteccion de objetos',
        algorithm: 'Transformers',
        efficiency: 'Lento',
        modeLabel: 'Solo imagen',
        status: 'ready',
        statusLabel: 'Listo',
        supportsWebcam: false,
        description: 'Reconoce y ubica objetos en imagenes cargadas con buen rendimiento visual. Es una alternativa fuerte para comparar resultados cuando una imagen tiene varios elementos.'
    }
];
